{% set name = "atk" %}
{% set major_minor = "2.32" %}
{% set version = major_minor + ".0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ major_minor }}/{{ name }}-{{ version }}.tar.xz
  sha256: cb41feda7fe4ef0daa024471438ea0219592baf7c291347e5a858bb64e4091cc

build:
  number: 2
  skip: true  # [win and vc<14]
  run_exports:
    # Good stability in the 2.x series:
    # https://abi-laboratory.pro/index.php?view=timeline&l=atk
    - {{ pin_subpackage("atk", max_pin="x") }}

requirements:
  build:
    - make  # [not win]
    - meson
    - ninja
    - python >=3.6
    - perl  # [not win]
    - pkg-config
    - {{ compiler('c') }}
  host:
    - glib
    - gobject-introspection 1.*
  run:
    - glib
    - gobject-introspection 1.*

test:
  requires:
    - pkg-config
  commands:
    # verify that libs get installed and can be located through pkg-config
    {% set pc = "atk" %}
    {% set lib = "atk-1.0" %}
    - test -f $PREFIX/lib/lib{{ lib }}${SHLIB_EXT}  # [unix]
    - test -f `pkg-config --variable=libdir --dont-define-prefix {{ pc }}`/lib{{ lib }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\{{ lib }}-0.dll exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=exec_prefix --dont-define-prefix {{ pc }}`) do if not exist "%%a/bin/{{ lib }}-0.dll" exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ lib }}.lib exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=libdir --dont-define-prefix {{ pc }}`) do if not exist "%%a/{{ lib }}.lib" exit 1  # [win]

    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gtk.org/
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: 'Accessibility Toolkit.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
